# Rutkowski Met. i techniki sztucznej inteligencji
# Deep Learning. Uczenie głębokie ...
# Python. Machine learning i deep learning ...
# Python. Uczenie maszynowe.
# Inteligentna sieć. Algorytmy przyszłości.